name: 'Deploy para o CloudFormation'

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

    if: "!contains(github.event.head_commit.message, '[skip ci]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
    
    steps:
      - name: Conectando-se ao seu repositorio
        uses: actions/checkout@v4 #https://github.com/actions/checkout

      #Configure AWS Credential
      - name: Step Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 #sobre https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      # Deploy CloudFormation S3 Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation S3 Stack"
        if: "contains(github.event.head_commit.message, '[s3]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1 #https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions
        with:
          name: s3-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 03_s3.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: >-
            pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}     

      # Deploy CloudFormation RDS Stack
      - name: Action AWS CloudFormation "Deployando a stack RDS no CloudFormation"
        if: "contains(github.event.head_commit.message, '[rds]')" # Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1 #https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions
        with:
          name: rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 04_rds.yml
          no-fail-on-empty-changeset: 1      
          parameter-overrides: >-
            pExportVpcStackName=vpc-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}

      # Deploy CloudFormation IAM Roles Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation IAM Roles Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[roles]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: roles-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 05_iam_roles.yml
          no-fail-on-empty-changeset: 1
          capabilities: CAPABILITY_NAMED_IAM  
          parameter-overrides: >-
            pExportSecretStackName=rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}

      #Deploy CloudFormation DMS Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation DMS Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[dms]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dms-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 06_dms.yml
          no-fail-on-empty-changeset: 1
          capabilities: CAPABILITY_NAMED_IAM 
          parameter-overrides: >-
            pExportVpcStackName=vpc-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportS3StackName=s3-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportRdsStackName=rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportRolesStackName=roles-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}            
            ,pExportSecretStackName=rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}

       # Deploy CloudFormation Glue Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation Glue Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[glue]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: glue-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 07_glue.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: >-
            pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}

      # Deploy CloudFormation Athena Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation Athena Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[athena]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: athena-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 08_athena.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: >-
            pExportS3StackName=s3-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}    

      # Deploy CloudFormation IAM Users Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation IAM Users Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[users]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: users-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 09_iam_users.yml
          no-fail-on-empty-changeset: 1
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            pExportRdsStackName=rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportS3StackName=s3-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportGlueStackName=glue-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pExportAthenaStackName=athena-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
            ,pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}

      # Deploy CloudFormation SES Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation SES Stack" #in ${{ steps.branch-name-generator.outputs.BRANCH_NAME }} branch
        if: "contains(github.event.head_commit.message, '[ses]')" #Caso a msg do commit nao contenha [skip ci] entra no IF, caso contrario nao
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ses-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 10_ses.yml
          no-fail-on-empty-changeset: 1
